"""initial migration

Revision ID: 1f115159062f
Revises: 
Create Date: 2023-12-13 02:57:09.838386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f115159062f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_info',
    sa.Column('actor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=2), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('movie_info',
    sa.Column('movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_name', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('move_box',
    sa.Column('movie_id', sa.String(length=10), nullable=False),
    sa.Column('box', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_info.movie_id'], ),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('movie_actor_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.String(length=10), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor_info.actor_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_info.movie_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actor_relation')
    op.drop_table('move_box')
    op.drop_table('movie_info')
    op.drop_table('actor_info')
    # ### end Alembic commands ###
