"""Add autoincrement to actor_id

Revision ID: a7bb858a7b4b
Revises: 41f4048fe2d6
Create Date: 2023-12-03 11:10:04.634362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bb858a7b4b'
down_revision = '41f4048fe2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor_info', schema=None) as batch_op:
        batch_op.alter_column('actor_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor_info', schema=None) as batch_op:
        batch_op.alter_column('actor_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
